### ISSUE TITLE
add support for H5P CSS hvp_alter_styles

### ISSUE THREAD

**Issue by danmarsden** [open-lms-open-source/moodle-theme_snap#162]
we've had a client request for adding support to the snap theme so that you can override content within the h5p activities - Essential theme is one that supports this already, - there's also a page here that covers how to do this in your theme:
https://h5p.org/documentation/for-developers/visual-changes

if we end up doing this we'll try to fire through a pull request.

**Comment by dvdcastro** [comment]
Thanks, we will review this.

**Comment by manfredsteger** [comment]
great suggestion. Would be great for custom design changes due to accessibility problems with H5P in different activities and display sizes.
