### ISSUE TITLE
ETA on public release of Snap for M3.8?

### ISSUE THREAD

**Issue by BirdyOz** [open-lms-open-source/moodle-theme_snap#177]
Hi there.

Given that Snap for Moodle 3.8 has now been released to OpenLMS hosted clients, how long until we might see a public release of the same version?

Thanks in eager expectation.

**Comment by dvdcastro** [comment]
Hello,

I think we already have. Sorry for the late response.
https://moodle.org/plugins/pluginversions.php?plugin=theme_snap
