### ISSUE TITLE
File Manager not working in Moodle 3.9

### ISSUE THREAD

**Issue by yewzy** [open-lms-open-source/moodle-theme_snap#179]
When the Snap theme is enabled, the file manager does not display, and drag and drop does not work. This issue does not occur when using the default Boost theme. It occurs on my production server and can be replicated in a local machine after a fresh install (with no plugins besides the theme). 

![snap](https://user-images.githubusercontent.com/4958053/89282941-e6863580-d67e-11ea-9a9e-452d3822cc14.png)

Moodle version: 3.9.1+ (Build: 20200730)

Snap version: 3.8.3 (2020061102) (Note: I did also tested it with the latest (master) version of Snap on Github)

Errors from Chrome Dev Tools: 
`Uncaught TypeError: Cannot read property 'on' of null
    at FileManagerHelper.setup_buttons (filemanager.js:28)
    at FileManagerHelper.initializer (filemanager.js:6)
    at FileManagerHelper._initHierarchy (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:279)
    at FileManagerHelper._baseInit (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:279)
    at FileManagerHelper.init (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:311)
    at FileManagerHelper._initBase (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:279)
    at FileManagerHelper.v (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:279)
    at FileManagerHelper.o (yui_combo.php?rollup/3.17.2/yui-moodlesimple-min.js:319)
    at new FileManagerHelper (filemanager.js:2)
    at Object.M.form_filemanager.init (filemanager.js:98)`

Related issues and discussions: 

https://tracker.moodle.org/browse/MDL-69172?focusedCommentId=805784&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel
https://moodle.org/mod/forum/discuss.php?d=406446#p1640841
https://moodle.org/mod/forum/discuss.php?d=405688
https://moodle.org/mod/forum/discuss.php?d=236743
https://moodle.org/mod/forum/discuss.php?d=408213 (This was started by me)

**Comment by alexmorrisnz** [comment]
This is still happening on the latest snap version

**Comment by jorgeschulz** [comment]
I am having the same problem, have you been able to solve it yet?

**Comment by dvdcastro** [comment]
@Rabecerra can you help us take a look at this one?

**Comment by jorgeschulz** [comment]
The file manager does not load the drag and drop interface. I had Moodle 3.7.3. When I upgraded to 3.8 this problem appeared. But even when I tried to upgrade to 3.9 and 3.10 the problem persists. I send as attachment the console information.
![file_manager_error](https://user-images.githubusercontent.com/65936156/106646793-dfc47680-656c-11eb-90e4-e97e9a8675fb.png)

**Comment by Rabecerra** [comment]
This problem happens with every file manager through Snap? Or it is only for specific pages? Also can you please test this with some other browsers?

**Comment by jorgeschulz** [comment]
Yes, in all of them, and with other browsers as well. For example, I am using Boost Campus theme and in the theme settings the file manager does not load either.
![Captura de Pantalla 2021-02-02 a la(s) 20 30 25](https://user-images.githubusercontent.com/65936156/106676756-3d20ed80-6596-11eb-9d79-fa902258dec9.png)

**Comment by jorgeschulz** [comment]
I don't know if it has to do with the same problem, but this page to post grading, comments and feedback files does not load well either.
![Captura de Pantalla 2021-02-03 a la(s) 01 30 09](https://user-images.githubusercontent.com/65936156/106698566-ce588a00-65bf-11eb-8d64-b079ba8e245d.png)

**Comment by Rabecerra** [comment]
I'm seeing we may have a particular problem with a Snap mustache that renders these file managers.
theme/snap/templates/core/filemanager_page_generallayout.mustache could be the main problem with this. If you have access to the code, can you help me testing if changing the name of this mustache in Snap adding .old at the end, so Snap can renders the mustache from core, helps with it? I'm seeing this issue from the threads in the first comment.

**Comment by jorgeschulz** [comment]
Thank you very much @Rabecerra for your attention, but I just solved both problems (file manager and grading page) I was able to solve the problem by manually updating Moodle, following this guide: https://docs.moodle.org/310/en/Upgrading
Previously I had done the updates using the Softaculous application from cPanel. I don't know if this had anything to do with the problem. What I finally did was to restore my site backups back to the old version 3.7.3, and from there I manually upgraded to version 3.10.1.
![Captura de Pantalla 2021-02-04 a la(s) 02 02 15](https://user-images.githubusercontent.com/65936156/106848306-74bf9080-668f-11eb-9ef2-e9aad4a9258d.png)

**Comment by Rabecerra** [comment]
I just wanted to narrow a little bit the problem with this, locally the file managers are working okay, we will check closely if something else happens with it. Thanks for the updates @jorgeschulz, let us know if you find something new with the file managers and Snap.

**Comment by unwiredtech** [comment]
`  buttonDeleteFile.on('click', function(e) {
                e.preventDefault();
                var dialogOptions = {};
                var filenames = this.getSelectedFiles();
`

The error on filemanager.js is this. "Canno read property on null". The issue is not a theme related, I think the latest moodle uses the latest jQuery?

**Comment by Shurikas** [comment]
Hello,
I have the same issue with the one theme where file manager not working. With the default theme it working

**Comment by ingdev-fr** [comment]
Hi everybody. I had the same problem on Moodle 4.3 and it was coming from the setting "debugtemplateinfo" in Moodle pannel administration. Deselecting him solved the problem ! it's explained : "Resulting HTML code produces validation errors and could render some scripts inoperable".

**Comment by loayalghshm** [comment]
> Hi everybody. I had the same problem on Moodle 4.3 and it was coming from the setting "debugtemplateinfo" in Moodle pannel administration. Deselecting him solved the problem ! it's explained : "Resulting HTML code produces validation errors and could render some scripts inoperable".

Thank you so much, it worked! Problem solved!

**Comment by martinezpenya** [comment]
I'm with moodle 4.1, same error, and I can't find "debugtemplateinfo". Where is?
I also changed the theme with no results.

**Comment by dmorillo77** [comment]
> Hi everybody. I had the same problem on Moodle 4.3 and it was coming from the setting "debugtemplateinfo" in Moodle pannel administration. Deselecting him solved the problem ! it's explained : "Resulting HTML code produces validation errors and could render some scripts inoperable".

I've just installed Moodle 4.05 (latest stable as of today), and it's still happening. When active, the option breaks javascript, not only in filemanager.js, but also in other places (like course/format/tiles, and some others).
