### ISSUE TITLE
Atto styling on 3.8.5

### ISSUE THREAD

**Issue by mrvinceo** [open-lms-open-source/moodle-theme_snap#188]
We just updated to 3.8.5 from 3.7, and have found that the Atto editor has lost all it's styling. It works on 3.8.3 (the version specified in version.php), so I'm guessing there was a change made to how Atto loads between the two versions.

<img width="439" alt="Screenshot 2020-11-26 at 09 47 52" src="https://user-images.githubusercontent.com/3594065/100335184-98e65d80-2fcc-11eb-87d7-35bce9a8ec23.png">

Could this be the change required: https://github.com/open-lms-open-source/moodle-theme_snap/commit/bf99283f63672eaaab28d1acaa4a3fecedd61327 ?

**Comment by mrvinceo** [comment]
Just to add; the recent change to master I referenced (thanks @dvdcastro) does fix this issue for the 3.8.3 version of snap when running on 3.8.5 version of Moodle.

**Comment by dvdcastro** [comment]
Thanks for finding out about this. We'll take a look soon.
