### ISSUE TITLE
Atto Editor acting up, misallignment of menu items in Atto

### ISSUE THREAD

**Issue by peter-lernyx** [open-lms-open-source/moodle-theme_snap#190]
Moodle 3.8.6. Snap 3.8.3

https://moodle.org/mod/forum/discuss.php?d=414606

**Comment by dvdcastro** [comment]
Hi @peter-lernyx

We solved this issue in 8f06e81

We've just responded on the forum thread also and re-release the 3.8.3 version on moodle.org

Let us know if you have any other problem

**Comment by peter-lernyx** [comment]
Hey, thanks for letting me know, I'll check it out and let you know how it goes. While I have you on, is there a release date for 3.9 stable? We're anxious to migrate to LTS..

**Comment by peter-lernyx** [comment]
Downloaded V2 from 'Plugins' and installed twice, purged all cashes, ran cron job manually, still no joy
![grafik](https://user-images.githubusercontent.com/75390480/101987955-272e3500-3c97-11eb-9b79-2f1441b58ab6.png)

**Comment by dvdcastro** [comment]
Hello @peter-lernyx,

> Downloaded V2 from 'Plugins' and installed twice, purged all cashes, ran cron job manually, still no joy

I'll take a look next week, really weird, it was reported to be fixed by someone else. 

Can you confirm you see this in `theme/snap/scss/_boost.scss` line `52`?
```scss
@import "moodle/atto";
```
>  is there a release date for 3.9 stable?

Most likely, it will be the 1st week of January. But I'll see if we can make that sooner.

**Comment by peter-lernyx** [comment]
H David, Yes I can confirm.

![grafik](https://user-images.githubusercontent.com/75390480/101991293-f99fb680-3cab-11eb-9602-1b06007e6c15.png)

Thanks for the release info. If it is fixed in 3.9, then there is hope..

**Comment by daveyboond** [comment]
> Downloaded V2 from 'Plugins' and installed twice, purged all cashes, ran cron job manually, still no joy
> ![grafik](https://user-images.githubusercontent.com/75390480/101987955-272e3500-3c97-11eb-9b79-2f1441b58ab6.png)

Just to add that I see the same behaviour as this on my production Moodle (Moo 3.8.6, Snap 3.8.3), but not on my test server (same combination). Must be related to settings.

**Comment by peter-lernyx** [comment]
I now completely re-installed Moodle 3.8.6 AND also SNAP, i.e. a complete reinstall in the same directory however using the existing database (just as you do in an update but with the same version) and Atto is straight again, i.o.w the above behaviour is no longer there. I used v2 of Snap 3.8.3

![grafik](https://user-images.githubusercontent.com/75390480/102103938-e3216880-3e2d-11eb-8f51-75a198c54d6e.png)

**Comment by dvdcastro** [comment]
Whoa, I guess a cache purge must have been needed maybe, since there is no version bump, but it's really weird b/c you said you had run the cache purge. Maybe it was a Browser caching issue?

**Comment by peter-lernyx** [comment]
David, I did all that. Had even re-installed just Atto before, but something somewhere happened that other people also have had happened to their install. Don't know what it is, but even after the complete reinstall my other issue persists (Exit Activity button) for which I have opened another issue here

**Comment by peter-lernyx** [comment]
confirmed on a second production site that this process works. Thanks David!
